export const products = [
  /* ================= CLOTH ================= */
  {
    id: 1,
    name: "Winter Jacket",
    categoryId: 1,
    basePrice: 5000,
    stock: 10,
    status: "ACTIVE",
    createdAt: "2024-01-01",
  },
  {
    id: 2,
    name: "Denim Jeans",
    categoryId: 1,
    basePrice: 3200,
    stock: 4,
    status: "ACTIVE",
    createdAt: "2023-12-15",
  },
  {
    id: 3,
    name: "Cotton Shirt",
    categoryId: 1,
    basePrice: 1800,
    stock: 2,
    status: "ACTIVE",
    createdAt: "2023-11-10",
  },
  {
    id: 4,
    name: "Wool Sweater",
    categoryId: 1,
    basePrice: 4200,
    stock: 0,
    status: "HIDDEN",
    createdAt: "2023-10-01",
  },
  {
    id: 5,
    name: "Formal Blazer",
    categoryId: 1,
    basePrice: 8500,
    stock: 1,
    status: "ACTIVE",
    createdAt: "2023-09-15",
  },

  /* ================= FURNITURE ================= */
  {
    id: 6,
    name: "Office Chair",
    categoryId: 2,
    basePrice: 12000,
    stock: 2,
    status: "HIDDEN",
    createdAt: "2023-11-01",
  },
  {
    id: 7,
    name: "Wooden Table",
    categoryId: 2,
    basePrice: 25000,
    stock: 5,
    status: "ACTIVE",
    createdAt: "2023-10-20",
  },
  {
    id: 8,
    name: "Bookshelf",
    categoryId: 2,
    basePrice: 15000,
    stock: 3,
    status: "ACTIVE",
    createdAt: "2023-09-10",
  },
  {
    id: 9,
    name: "Sofa Set",
    categoryId: 2,
    basePrice: 65000,
    stock: 1,
    status: "ACTIVE",
    createdAt: "2023-08-01",
  },
  {
    id: 10,
    name: "Dining Chair",
    categoryId: 2,
    basePrice: 7000,
    stock: 6,
    status: "ACTIVE",
    createdAt: "2023-12-01",
  },

  /* ================= COSMETIC ================= */
  {
    id: 11,
    name: "Face Cream",
    categoryId: 3,
    basePrice: 1500,
    stock: 12,
    status: "ACTIVE",
    createdAt: "2024-01-10",
  },
  {
    id: 12,
    name: "Perfume",
    categoryId: 3,
    basePrice: 4500,
    stock: 3,
    status: "ACTIVE",
    createdAt: "2023-12-01",
  },
  {
    id: 13,
    name: "Lipstick Pack",
    categoryId: 3,
    basePrice: 2200,
    stock: 0,
    status: "HIDDEN",
    createdAt: "2023-11-01",
  },
  {
    id: 14,
    name: "Hair Oil",
    categoryId: 3,
    basePrice: 900,
    stock: 8,
    status: "ACTIVE",
    createdAt: "2023-12-15",
  },
  {
    id: 15,
    name: "Makeup Kit",
    categoryId: 3,
    basePrice: 7800,
    stock: 2,
    status: "ACTIVE",
    createdAt: "2023-10-10",
  },

  /* ================= ELECTRONICS ================= */
  {
    id: 16,
    name: "Smartphone",
    categoryId: 4,
    basePrice: 35000,
    stock: 4,
    status: "ACTIVE",
    createdAt: "2023-11-20",
  },
  {
    id: 17,
    name: "Bluetooth Speaker",
    categoryId: 4,
    basePrice: 6500,
    stock: 7,
    status: "ACTIVE",
    createdAt: "2023-12-10",
  },
  {
    id: 18,
    name: "LED TV",
    categoryId: 4,
    basePrice: 72000,
    stock: 1,
    status: "ACTIVE",
    createdAt: "2023-09-01",
  },
  {
    id: 19,
    name: "Laptop",
    categoryId: 4,
    basePrice: 95000,
    stock: 2,
    status: "HIDDEN",
    createdAt: "2023-08-15",
  },
  {
    id: 20,
    name: "Power Bank",
    categoryId: 4,
    basePrice: 2800,
    stock: 15,
    status: "ACTIVE",
    createdAt: "2024-01-05",
  },

  /* ================= FOOTWEAR ================= */
  {
    id: 21,
    name: "Running Shoes",
    categoryId: 5,
    basePrice: 8500,
    stock: 6,
    status: "ACTIVE",
    createdAt: "2023-12-05",
  },
  {
    id: 22,
    name: "Leather Boots",
    categoryId: 5,
    basePrice: 14500,
    stock: 2,
    status: "ACTIVE",
    createdAt: "2023-10-01",
  },
  {
    id: 23,
    name: "Casual Sandals",
    categoryId: 5,
    basePrice: 3200,
    stock: 10,
    status: "ACTIVE",
    createdAt: "2023-12-20",
  },
  {
    id: 24,
    name: "Formal Shoes",
    categoryId: 5,
    basePrice: 9800,
    stock: 1,
    status: "ACTIVE",
    createdAt: "2023-09-01",
  },
  {
    id: 25,
    name: "Flip Flops",
    categoryId: 5,
    basePrice: 1200,
    stock: 20,
    status: "ACTIVE",
    createdAt: "2024-01-12",
  },

  /* ================= HOME DECOR ================= */
  {
    id: 26,
    name: "Wall Clock",
    categoryId: 6,
    basePrice: 3500,
    stock: 8,
    status: "ACTIVE",
    createdAt: "2023-11-15",
  },
  {
    id: 27,
    name: "Table Lamp",
    categoryId: 6,
    basePrice: 4200,
    stock: 5,
    status: "ACTIVE",
    createdAt: "2023-12-01",
  },
  {
    id: 28,
    name: "Curtain Set",
    categoryId: 6,
    basePrice: 6800,
    stock: 2,
    status: "ACTIVE",
    createdAt: "2023-10-10",
  },
  {
    id: 29,
    name: "Flower Vase",
    categoryId: 6,
    basePrice: 2600,
    stock: 0,
    status: "HIDDEN",
    createdAt: "2023-09-01",
  },
  {
    id: 30,
    name: "Carpet Rug",
    categoryId: 6,
    basePrice: 18500,
    stock: 3,
    status: "ACTIVE",
    createdAt: "2023-08-20",
  },
];
